<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>logo\logo.ico</ApplicationIcon>
    <Version>4.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="6.0.4" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="logo\logo100.png" />
    <Resource Include="logo\logo50.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Installer\**\*.cs" />
    <Compile Remove="Tests\**\*.cs" />
  </ItemGroup>

</Project>
